version: 2.1

defaults: &defaults
  working_directory: ~/project/vue
  docker:
    - image: circleci/node:lts-browsers

aliases:
  - &restore-yarn-cache
    key: v2-vue-cli-{{ checksum "yarn.lock" }}

  - &save-yarn-cache
    key: v2-vue-cli-{{ checksum "yarn.lock" }}
    paths:
      - node_modules/
      - ~/.cache

workflow_filters: &filters
  filters:
    branches:
      ignore:
      - docs

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: yarn --network-timeout 600000
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project/vue
            - .cache/Cypress

  e2e:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: ./scripts/e2e-test/run-e2e-test.sh

  core:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn test -p cli,cli-service,cli-shared-utils

workflows:
  version: 2
  test:
    jobs:
      - install:
          <<: *filters
      - core:
          <<: *filters
          requires:
            - install
      - typescript:
          <<: *filters
          requires:
            - install