version: 2.1
orbs:
  slack: circleci/slack@4.4.4
jobs:
  deploy:
    docker:
      - image: circleci/node:8-browsers
 
    working_directory: ~/repo
 
    steps:
      - checkout
      - run: npm install
      - run: 
          name: Deploy Master Branch
          command: |
            sudo apt-get update
            sudo apt-get -qq install git-ftp
            echo "Deploying project ..."
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

 
workflows:
  default:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
      - notify:
          filters:
              branches:
                only: main
          context: slack-notify